<a href="https://colab.research.google.com/github/samiran097/tensorflow-2.X-basics/blob/main/tf2_x_low_level_API.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Tensor uses GPU
### Numpy uses CPU

## Tensorflow 2.x low level API

In [ ]:
import tensorflow as tf

# What is keras ? Is it high level API or low level

### Keras is an high level API [in very less code we would achieve lot of functationalities]

## Tensor Constant

### Tensor : Multi dimentional arrays [In DL we use these matrices , those will be handled by tensor]

In [ ]:
const = tf.constant(43)

In [ ]:
const

<tf.Tensor: shape=(), dtype=int32, numpy=43>

In [ ]:
const.numpy()

43

In [ ]:
## specify the datatype
const = tf.constant(43,dtype=tf.int64)
const

<tf.Tensor: shape=(), dtype=int64, numpy=43>

In [ ]:
## define a constant matrix
const_mat = tf.constant([[4,2],[9,5]])
const_mat

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 2],
       [9, 5]], dtype=int32)>

In [ ]:
const_mat * 4

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[16,  8],
       [36, 20]], dtype=int32)>

In [ ]:
const_mat.shape

TensorShape([2, 2])

In [ ]:
const_mat.dtype

tf.int32

### observe: Increase the no. of hidden layers & observe what happens to size of the model that you save ==> increase

### Query: Before & after training will the model size will remain same or increase or decrease ? ==>remains same

### If you increase the depth of the model (increase the hidden layer) then during prediction the model will take more time compared to another model with less depth

### Commonly used method

In [ ]:
tf.ones(shape = (2,3)) # this could be utilized during bias and weights initialization

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape = (2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
tf.ones(shape = (2,3)) * 7

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[7., 7., 7.],
       [7., 7., 7.]], dtype=float32)>

In [ ]:
## Add operations - cond.  the shape of the matrices should be same
const1 = tf.constant([[11,3,4],[3,4,5]])
const2 = tf.constant([[7,9,5],[3,4,5]])


In [ ]:
tf.add(const1,const2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[18, 12,  9],
       [ 6,  8, 10]], dtype=int32)>

In [ ]:
const1 + const2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[18, 12,  9],
       [ 6,  8, 10]], dtype=int32)>

In [ ]:
# Random constant
x = tf.random.normal(shape = (2,2),mean=0,stddev=1.0)
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.1644264 , -0.70312357],
       [-1.4109277 ,  0.54066956]], dtype=float32)>

In [ ]:
x = tf.random.uniform(shape=(2,2),minval=0,maxval=10)
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.865916 , 3.290447 ],
       [3.1456745, 9.992277 ]], dtype=float32)>

In [ ]:
x = tf.random.uniform(shape=(2,2),minval=0,maxval=10,dtype=tf.int32)
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 1],
       [8, 6]], dtype=int32)>

In [ ]:
# Variables
var1= tf.Variable(45.55,dtype=tf.float16)

var2 = tf.Variable([[2,3],[4,5]])

var1

## fload16 / float32 / floatN, will have varing size & based on target deployment the accuracy gets affected

<tf.Variable 'Variable:0' shape=() dtype=float16, numpy=45.56>

In [ ]:
var2.numpy()

array([[2, 3],
       [4, 5]], dtype=int32)

In [ ]:
# Assigning
## Reassign a variable , var.assign() - used during weight update
var1 = tf.Variable(45.4,dtype=tf.float16)
var1

<tf.Variable 'Variable:0' shape=() dtype=float16, numpy=45.4>

In [ ]:
var1.assign(99)
var1

<tf.Variable 'Variable:0' shape=() dtype=float16, numpy=99.0>

In [ ]:
## reshaping operation - used in image formating
tensor = tf.Variable([[[10,11,12],[13,15,18]],[[10,11,12],[13,15,18]]])
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[10, 11, 12],
        [13, 15, 18]],

       [[10, 11, 12],
        [13, 15, 18]]], dtype=int32)>

In [ ]:
reshape_val = tf.reshape(tensor,shape=(2,6))
reshape_val

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[10, 11, 12, 13, 15, 18],
       [10, 11, 12, 13, 15, 18]], dtype=int32)>

In [ ]:
# Flattening operation
reshape_val = tf.reshape(tensor,shape=(1,12))
reshape_val

<tf.Tensor: shape=(1, 12), dtype=int32, numpy=array([[10, 11, 12, 13, 15, 18, 10, 11, 12, 13, 15, 18]], dtype=int32)>

In [ ]:
# rank of the tensor --> is the no. of dimensions
tf.rank(reshape_val)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
# Slicing - croping of image
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[10, 11, 12],
        [13, 15, 18]],

       [[10, 11, 12],
        [13, 15, 18]]], dtype=int32)>

In [ ]:
tensor[0, 1, 1]

<tf.Tensor: shape=(), dtype=int32, numpy=15>

In [ ]:
tensor[:,:,:]

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[10, 11, 12],
        [13, 15, 18]],

       [[10, 11, 12],
        [13, 15, 18]]], dtype=int32)>

In [ ]:
tensor[0,:,:]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 11, 12],
       [13, 15, 18]], dtype=int32)>

In [ ]:
tensor[0,:,1:]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [15, 18]], dtype=int32)>

## Mathematical Operations

In [ ]:
a = tf.random.normal((2,3))
b = tf.random.normal((2,3))

c = a + b
c

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 3.836577  ,  0.15468991, -1.6021236 ],
       [ 1.7868885 , -0.9830315 , -0.23151112]], dtype=float32)>

In [ ]:
tf.square(c)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[14.719322  ,  0.02392897,  2.5668    ],
       [ 3.1929705 ,  0.966351  ,  0.0535974 ]], dtype=float32)>

In [ ]:
tf.exp(c)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[46.366486  ,  1.1672959 ,  0.20146821],
       [ 5.970845  ,  0.37417507,  0.7933339 ]], dtype=float32)>

In [ ]:
# Element wise multiplication
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[10, 11, 12],
        [13, 15, 18]],

       [[10, 11, 12],
        [13, 15, 18]]], dtype=int32)>

In [ ]:
tensor * tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[100, 121, 144],
        [169, 225, 324]],

       [[100, 121, 144],
        [169, 225, 324]]], dtype=int32)>

## Broadcasting in Tensorflow

In [ ]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[10, 11, 12],
        [13, 15, 18]],

       [[10, 11, 12],
        [13, 15, 18]]], dtype=int32)>

In [ ]:
scalar = 4
tensor * scalar

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[40, 44, 48],
        [52, 60, 72]],

       [[40, 44, 48],
        [52, 60, 72]]], dtype=int32)>

In [ ]:
tensor + scalar

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[14, 15, 16],
        [17, 19, 22]],

       [[14, 15, 16],
        [17, 19, 22]]], dtype=int32)>

## Matrix Multiplication -- > used during W = W + eta*Loss

In [ ]:
mat_u = tf.constant([[6,7,7]])
mat_v = tf.constant([[3,4,3]])

In [ ]:
mat_u * mat_v # This results in elementwise multiplication

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[18, 28, 21]], dtype=int32)>

In [ ]:
tf.matmul(mat_u,tf.transpose(mat_v)) # transpose is used to follow mult rules

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[67]], dtype=int32)>

In [ ]:
# Alternative multiplation method
tf.transpose(mat_v) @ mat_u 

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[18, 21, 21],
       [24, 28, 28],
       [18, 21, 21]], dtype=int32)>

In [ ]:
 mat_u  @ tf.transpose(mat_v)

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[67]], dtype=int32)>

In [ ]:
### Casting method in tf to change the datatype
tf.cast(mat_u,dtype=tf.int16) ### << can be utilized in quantization --> {used during deployment}

<tf.Tensor: shape=(1, 3), dtype=int16, numpy=array([[6, 7, 7]], dtype=int16)>

In [ ]:
tf.cast(tf.constant(444.1234),dtype=tf.int32)

<tf.Tensor: shape=(), dtype=int32, numpy=444>

## Ragged tensors
>> nested variable length arrays --> use case in NLP, where the number of words in each line will be different

In [ ]:
ragged = tf.ragged.constant([[1,2,3,4,5], [], [1,2,3]])

In [ ]:
ragged

<tf.RaggedTensor [[1, 2, 3, 4, 5], [], [1, 2, 3]]>

In [ ]:
# Throws error
ragged = tf.constant([[1,2,3,4,5], [], [1,2,3]])

ValueError: ignored

In [ ]:
ragged.shape # (3,None) >> (# of rows, columns could varry)

TensorShape([3, None])

In [ ]:
# Checking individual shape of matrix
ragged[0,:].shape

TensorShape([5])

In [ ]:
ragged[1,:].shape

TensorShape([0])

## Squared difference of tensors

In [ ]:
varx = [1,2,3,4,5,6]
vary = 2

tf.math.squared_difference(varx,vary) # used during calculating errors

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 1,  0,  1,  4,  9, 16], dtype=int32)>

In [ ]:
pred = [1,2,3,4,5,6]
actual = [1,1,1,1,1,1]

tf.math.squared_difference(pred ,actual) # used duringcalculating errors

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 0,  1,  4,  9, 16, 25], dtype=int32)>

## Calculating mean

In [ ]:
num = tf.constant([[1,2], [3,4]],dtype = tf.float32)
num

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [ ]:
tf.reduce_mean(num) # MEan of all the elements in the array

<tf.Tensor: shape=(), dtype=float32, numpy=2.5>

In [ ]:
tf.reduce_mean(num,axis = 0) # row wise mean

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [ ]:
tf.reduce_mean(num,axis = 1) # column wise mean

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.5, 3.5], dtype=float32)>

In [ ]:
tf.reduce_mean(num,axis = 1,keepdims=True) # column wise mean but keeps the dimention of the array

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.5],
       [3.5]], dtype=float32)>